#===================================================
# Description: Build v8 enginer using GitHub Actions
# Author: t1an5t
#===================================================


name: BUILD chromium

on:
  push:
    branches: [ main ]
  watch:
    types: started

env:
  PATCH_FLAG: false
  COMMIT: e0a58f83255d1dae907e2ba4564ad8928a7dedf4	
  DEPOT_UPLOAD: false
  SRC_UPLOAD: true
  BINARY_UPLOAD: false

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    if: github.event.repository.owner.id == github.event.sender.id 	
    
    steps:
    - name: Checkout
      uses: actions/checkout@master
      
    # init ubuntu1804 environment
    - name: init env
      run: |
        sudo apt-get update
        sudo apt-get -y install pkg-config git subversion curl wget build-essential xz-utils zip p7zip-full
    
    # get depot_tools
    - name: depot_tools
      run: |
        git clone https://chromium.googlesource.com/chromium/tools/depot_tools.git
        echo export PATH=\"\$PATH:`pwd`/depot_tools/\" >> ~/.bash_profile
    
    # fetch v8 source code
    - name: fetch chromium
      run: |
        mkdir chromium && cd chromium
        source ~/.bash_profile
        fetch chromium
    
    # patch source code
    - name: patch v8
      if: env.PATCH_FLAG == 'true' && !cancelled()
      run: |
        cd v8
        git reset --hard $COMMIT
        cd ..
        
    - name: build chromium
      run: |
        cd chromium
        source ~/.bash_profile
        gclient sync -f
    
    # compress this file
    - name: zip depot_tools
      if: env.DEPOT_UPLOAD == 'true' && !cancelled()
      run: |
        zip -q -r depot_tools.zip depot_tools
        
    # 7zip v8 src
    - name: 7zip chromium_src
      run: |
        zip -q -r chromium.zip chromium
        7z a chromium.7z ./chromium.zip -v2048m
    
    # upload depot_tools.zip to cowtransfer
    - name: upload depot_tools
      if: env.DEPOT_UPLOAD == 'true' && !cancelled()
      run: |
        curl -fsSL git.io/file-transfer | sh
        ./transfer wss --block 2621440 -s -p 64 --no-progress depot_tools.zip 2>&1
   
    # upload v8.zip to cowtransfer
    - name: upload chromium_src
      if: env.SRC_UPLOAD == 'true' && !cancelled()
      run: |
        curl -fsSL git.io/file-transfer | sh
        ./transfer wss --block 2621440 -s -p 64 --no-progress v8.7z.001 2>&1
        ./transfer wss --block 2621440 -s -p 64 --no-progress v8.7z.002 2>&1
        ./transfer wss --block 2621440 -s -p 64 --no-progress v8.7z.003 2>&1
        ./transfer wss --block 2621440 -s -p 64 --no-progress v8.7z.004 2>&1
        ./transfer wss --block 2621440 -s -p 64 --no-progress v8.7z.005 2>&1
        ./transfer wss --block 2621440 -s -p 64 --no-progress v8.7z.006 2>&1
        ./transfer wss --block 2621440 -s -p 64 --no-progress v8.7z.007 2>&1
        ./transfer wss --block 2621440 -s -p 64 --no-progress v8.7z.008 2>&1
        ./transfer wss --block 2621440 -s -p 64 --no-progress v8.7z.009 2>&1
        ./transfer wss --block 2621440 -s -p 64 --no-progress v8.7z.010 2>&1

